added points animation assertion
MariaMoroz/PWTSPWeb pull request #13
Opened 2024-01-21 00:05 UTC by MariaMoroz

2024-01-21 18:46 UTC, yuliahar requested changes

2024-01-21 18:46 UTC, yuliahar commented on tests/testHomePage.spec.ts
> +        await expect(pm.homePage.circularProgressbar).toHaveScreenshot("pointsBar.png");
Please use expect(await pm.homePage.circularProgressbar.screenshot()).toMatchSnapshot(
			"pointsBar.png",
			{ threshold: 0.6 }
		);
		to make screenshot comparison.

2024-01-21 18:46 UTC, yuliahar commented on tests/testHomePage.spec.ts
> +        await page.waitForTimeout(800);
add const ANIMATION_TIME = 800 and use it here

2024-01-21 19:52 UTC, yuliahar commented on tests/testHomePage.spec.ts
> +        await expect(pm.homePage.circularProgressbar).toHaveScreenshot("pointsBar.png");
Hm, playwright documentation says: use .toHaveScreenshot for comparing screenshots. Could you please check that test will failed if images are different?

2024-01-23 01:38 UTC, MariaMoroz commented on tests/testHomePage.spec.ts
> +        await expect(pm.homePage.circularProgressbar).toHaveScreenshot("pointsBar.png");
Yes, I rechecked many times and method toHaveScreenshot() works correctly

2024-01-23 01:42 UTC, MariaMoroz commented on tests/testHomePage.spec.ts
> +        await page.waitForTimeout(800);
done

2024-01-23 03:08 UTC, merged